### ISSUE TITLE
Add a test of a POD with init containers and a test of a POD with containers that fail

### ISSUE THREAD

**Issue by Bianco95** [interTwin-eu/vk-test-set#7]
Need to expand test pods with one POD that has init containers, like the following one
```
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-1
  namespace: interlink

spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: virtual-node

  initContainers:
  - name: init-cnt1
    image: ghcr.io/grycap/cowsay
    command: ["/bin/sh", "-c"]
    args: ["echo 'init cnt 1. now sleep'; sleep 5; exit 0"]
    imagePullPolicy: Always

  - name: init-cnt2
    image: ghcr.io/grycap/cowsay
    command: ["/bin/sh", "-c"]
    args: ["echo 'init cnt 2. now sleep'; sleep 5; exit 0"]
    imagePullPolicy: Always

  containers:
  - name: successful-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["exit 0"]
    imagePullPolicy: Always

  dnsPolicy: ClusterFirst

  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
      effect: NoSchedule
      ``` 
      
 And a POD with a failed container, like the following one:
 ```
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-1
  namespace: interlink

spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: virtual-node

  containers:
  - name: successful-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["exit 0"]
    imagePullPolicy: Always

  - name: hello-world
    image: ghcr.io/grycap/cowsay
    command: ["/bin/sh", "-c"]
    args: ["echo 'hello world'; sleep 5"]
    imagePullPolicy: Always

  - name: fail-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["exit 1"]  # FORCE FAIL EXIT CODE
    imagePullPolicy: Always

  dnsPolicy: ClusterFirst

  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
      effect: NoSchedule
 ```
